### ISSUE TITLE
Bug where contents of document pop up does not update if pop up was left open but a new receipt with the same name has been issued with new contents.

### ISSUE THREAD

**Issue by clawyq** [CS2103-AY1819S1-W16-4/main#178]
For example, imagine a situation where a receipt is issued with the below contents:
1. Patient: Bryan
2. IC: S9612345X
3. Medicine Dispensed: 10 units of Panadol, lets assume each unit of Panadol costs $2.00.

The total price reflected on the receipt will be  $30.00 (consultation flat fee) + $2.00 * 10 = **$50.00**.
The receipt HTML file will also be named **"Receipt_For_Bryan_S9612345X.html"**.

Imagine the situation where the doctor realises that Bryan needs more medication, and issues **15 units of Panadol**  instead, amounting to a new total of $30.00 (consultation flat fee) + $2.00 * 15 = **$60.00**.

However, as the receipt to be generated is also named **"Receipt_For_Bryan_S9612345X.html"**, the pop-up will continue to display the old contents (ie. total price is $50.00)

This is wrong behaviour as the pop-up should reflect the change in total price.
Note that this only occurs if the initial pop-up is minimised. If it was closed, the subsequent pop-up will reflect the correct content.

**Comment by ChesterSng** [comment]
Add a timestamp at the end of the filename

**Comment by clawyq** [comment]
Doesn't work :/

**Comment by ChesterSng** [comment]
Maybe you can try to close any existing window of the same type first before opening? 👍
