### ISSUE TITLE
MC, Referral and Receipt classes

### ISSUE THREAD

**Issue by blewjy** [CS2103-AY1819S1-W16-4/main#37]
Create interface with inheritting classes MC, Referral, Receipt.
Have an API for all three of them.
Probably a generic generate method in the interface will be good so that all calls are just call .generate(args...)

**Comment by clawyq** [comment]
Receipt class has been completed.

**Comment by clawyq** [comment]
All classes have been completed. Enhancements to these classes will be following this issue. Issue will hence be closed.
